apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zcqq3nh1b-go 
  janus-idp.io/tekton: zcqq3nh1b-go
  backstage.io/kubernetes-id: zcqq3nh1b-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zcqq3nh1b-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml